[username]
style_user = "white bold"
style_root = "red bold"
format = "[](bold blue)  [$user](bold white) in "
disabled = false
show_always = true

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[󰥮](bold yellow) "     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[✗](bold red)"
#  
# configure directory
[directory]
read_only = " "
truncation_length = 10
truncation_symbol = "…/"
truncate_to_repo = true # truncates directory to root folder if in github repo
style = "bold italic yellow"

[git_commit]
disabled = true

[git_state]
disabled = true

[git_status]
disabled = true
