splash = false

wallpaper {
    monitor = eDP-1
    path = ~/.config/assets/wallpapers/wp3.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = ~/.config/assets/wallpapers/wp3.jpg
    fit_mode = cover
}

